#!/bin/bash
# run_cefr.sh
#
# Generate Spanish CEFR lesson videos. Each level is split into 10 lessons,
# words sorted by frequency (most common first).
#
# First run: ./generate_vocab.py to create vocab/ JSONs (one-time).
#
# Usage:
#   ./run_cefr.sh <level>              # all 10 lessons for that CEFR level
#   ./run_cefr.sh <level> <lesson>     # single lesson
#
# Examples:
#   ./run_cefr.sh A1          # all 10 lessons for A1 (~30 words each)
#   ./run_cefr.sh B2 5        # B2 lesson 5 only
#
# Output: output/<level>/lesson_<NN>/
#
# CEFR Levels (approx word counts, generated by generate_vocab.py):
#   A1: 300 words  (~30/lesson)    B2: 800 words  (~80/lesson)
#   A2: 400 words  (~40/lesson)    C1: 1000 words (~100/lesson)
#   B1: 600 words  (~60/lesson)    C2: 1200 words (~120/lesson)
#
# Requires: OPENAI_API_KEY, python3, ffmpeg

set -e

LEVEL=${1:?"Usage: ./run_cefr.sh <level> [lesson]   (level: A1, A2, B1, B2, C1, C2)"}
LESSON=${2:-all}
LESSONS_PER_LEVEL=10
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Validate level
case "$LEVEL" in
    A1|A2|B1|B2|C1|C2) ;;
    *) echo "Error: Level must be one of: A1, A2, B1, B2, C1, C2"; exit 1 ;;
esac

if [ -z "$OPENAI_API_KEY" ]; then
    echo "Error: OPENAI_API_KEY not set"
    echo "  export OPENAI_API_KEY=sk-..."
    exit 1
fi

# Check vocab exists
if [ ! -f "${SCRIPT_DIR}/vocab/${LEVEL}.json" ]; then
    echo "Error: vocab/${LEVEL}.json not found"
    echo "  Run first: python generate_vocab.py"
    exit 1
fi

run_lesson() {
    local lvl=$1
    local les=$2
    local out_dir="${SCRIPT_DIR}/output/${lvl}/lesson_$(printf '%02d' "$les")"

    echo ""
    echo "════════════════════════════════════════════"
    echo "  CEFR $lvl · Lesson $les/$LESSONS_PER_LEVEL"
    echo "════════════════════════════════════════════"

    mkdir -p "$out_dir"

    # Step 0: Generate dialogue from vocab
    echo ">> Generating dialogue..."
    python3 "${SCRIPT_DIR}/generate_dialogue.py" \
        --level "$lvl" \
        --lesson "$les" \
        --lessons_per_level "$LESSONS_PER_LEVEL" \
        --vocab_dir "${SCRIPT_DIR}/vocab" \
        --output "$out_dir/dialogue.txt"

    # Step 1: TTS audio + SRT subtitles
    echo ">> Generating TTS audio + subtitles..."
    python3 "${SCRIPT_DIR}/step1_tts.py" \
        --input "$out_dir/dialogue.txt" \
        --output_dir "$out_dir"

    # Step 2: Burn subtitles into video
    echo ">> Rendering video..."
    bash "${SCRIPT_DIR}/step2_video.sh" "$out_dir"

    # Step 3: Word-by-word gloss CSV
    echo ">> Generating gloss..."
    python3 "${SCRIPT_DIR}/step3_gloss.py" \
        --input "$out_dir/dialogue.txt" \
        --output "$out_dir/gloss_output.csv"

    echo ""
    echo "Done: CEFR $lvl Lesson $les → $out_dir/"
}

# ── Run ────────────────────────────────────────────────────────────────────

if [ "$LESSON" = "all" ]; then
    echo "Generating all $LESSONS_PER_LEVEL lessons for CEFR $LEVEL"
    for les in $(seq 1 $LESSONS_PER_LEVEL); do
        run_lesson "$LEVEL" "$les"
    done
    echo ""
    echo "════════════════════════════════════════════"
    echo "  All $LESSONS_PER_LEVEL lessons for CEFR $LEVEL complete!"
    echo "  Output: output/${LEVEL}/"
    echo "════════════════════════════════════════════"
else
    if [ "$LESSON" -lt 1 ] || [ "$LESSON" -gt "$LESSONS_PER_LEVEL" ]; then
        echo "Error: Lesson must be 1-$LESSONS_PER_LEVEL"
        exit 1
    fi
    run_lesson "$LEVEL" "$LESSON"
fi
