(function(g){function H(a){"$ignore"===a&&(f.define=y,y=null)}function I(a,c,b){b||(b=c,c=[]);q=0;B[a]=!0;r(c,function(){m[a]=b.apply(null,arguments)})}function r(){n.push(arguments);C()}function C(){var a,c;if(n.length){var b=n;n=[];var d={};k=[];for(a=b.length;a--;){var e=[];var h=!0;for(c=b[a][0].length;c--;){var p=b[a][0][c];p in m?e[c]=m[p]:(d[p]||B[p]||(k.push(p),d[p]=!0),h&&(n.push(b[a]),h=!1))}if(h){var J=!0;try{b[a][1].apply(null,e)}catch(K){t(K,"runtime")}}}J?C():n.length&&!u&&(u=z(D,100))}}
function D(){var a,c=[];u=E(u);if(!q){A=E(A);for(a=k.length;a--;){var b=k[a];v[b]?(k.splice(a,1),2>v[b]&&(v[b]++,c.push(b))):v[b]=1}q=k.length;c.length&&t(Error("Modules '"+c.join("', '")+"' failed to load"),"loadFailed");if(q){A=z(L,6E4);try{var d=l.createElement("script");d.src=M+"//s2.adform.net/mink/636/s2.adform.net/load/v/0.0.260/e/"+m.$env.$hash()+"/i/"+m.$ignore+"/r:"+k.sort().join(":");var e=l.__gEBTN__("script")[0];d.onerror=N;e?e.parentNode.insertBefore(d,e):(l.body||l.head).appendChild(d)}catch(h){t(h,"script_insert")}}}}
function N(){w("response_error",this.src)}function L(){q=0;D()}function w(a,c,b,d){var e=[],h=g.Image;Math.random()<(b||.03)&&(e.push((x&&x.host||"//track.adform.net")+"/serving/jslog/"),e.push("?src="),e.push(encodeURIComponent(a)),e.push("&msg="),e.push(encodeURIComponent(c)),e.push("&level="),e.push(encodeURIComponent(d||"error")),a=h?new h(1,1):l.createElement("img"),a.src=e.join(""))}function t(a,c){var b=""+(a.stack||a);0>b.indexOf(a.message||"")&&(b=a+"\n"+b);z(function(){throw b;},0);w(c,
b)}function F(){for(var a=arguments,c=0,b=a.length,d=[];c<b;c++)O(a[c])||d.push(a[c]);return d.length?G.apply(f,d):f.length}function O(a){function c(e){e.apply(null,a.slice(1))}var b=a[0],d=m[b];d?c(d):r([b],c)}var y,G,u,A,k,f=g._adfq||(g._adfq=[]),l=g.document,z=g.setTimeout,E=g.clearTimeout,x=g.Adform,M=x&&"https:"===(x.shost||"").split("/")[0]||"https:"===g.location.protocol?"https:":"http:",m={require:r,$boot:{window:g,require:r,rethrow:t,log:w,deprecate:function(a,c,b){var d=!1;return function(){d||
(w("deprecate",c,b,"info"),d=!0);return a.apply(this,arguments)}}}},q=0,n=[],B={},v={};l.__gEBTN__=l.getElementsByTagName;(function(){if(f.define)y=f.define,f.define=H;else{G=f.push;f.define=I;f.push=F;var a=f.slice();f.length=0;F.apply(f,a)}})()})(window);
(function(a,i,c,b,U,R,T,V,W,e,m,Q,O,v,M,N,x,y,S,X,P,L,f){
a(i,[c],function(c){c=c.window;var a=c.Adform||{},d=a.ET||{},b=a.RMB||{},e=b.Content||{};b.Type=b.Type||{};b.Content=e;a.ET=d;a.RMB=b;return c.Adform=a});
a(b,[c],function(S){function xa(h){return h}function ya(){function h(){for(var b=1,c=t;b<k.length&&!k[b];b++)c=c.parent;try{return c==c.Function("return window")()}catch(g){}}function u(b,c){var g=c.charAt(0).toUpperCase()+c.slice(1);return n(b,"ms"+g,"moz"+g,"webkit"+g,c)}function n(b){for(var c=arguments,g=c.length;--g;)if(c[g]in b)return c[g]}function e(b,c){return 0<=(""+b).toLowerCase().indexOf(c.toLowerCase())}var a=S.window,f=a.document,A=f.documentElement,l=a.navigator,t=a.parent,
q=l.vendor,d=l.userAgent,B=a.location||{},C=a.top,D=f.createElement("div"),k=function(b){for(var c,g=100,m=b.top,E=[!0];--g&&b&&b!=m&&b!=b.parent;){try{c=!!(b=b.parent).Image}catch(Ca){c=!1}E.push(c)}return E}(a),v=a!=t,I=!v||k[1],w=!v||k[k.length-1],T=v&&h(),U=u(f,"hidden"),V=!!U,F=/MSIE|Trident/i.test(d),W=F&&("Microsoft Internet Explorer"===l.appName&&/MSIE (\d+[\.\d]*)/i.exec(d)||/rv:(\d+[\.\d]*)/i.exec(d))?parseFloat(RegExp.$1):-1;D=n(D,"addEventListener");var X=e(d,"Macintosh"),G=e(q,"apple computer"),
J=e(d,"ipad"),K=e(d,"iphone"),r=J||K;var x=r&&(x=/\sos\s(\d+)_\d+/i.exec(d))&&(x=4<x[1]>>0);var L=e(q,"google"),M=!r&&e(d,"android"),Y="ontouchstart"in f||"ontouchstart"in a,N=(G||L)&&/(chrome|crios)+\/[\d\.]+\s/i.test(d),za=N&&/[chrome|crios]+\/([\d\.]+)\s/i.exec(d)[1],H=/Firefox\/[\d\.]+/i.test(d),Z=e(d,"opera");q=e(d,"opr")&&e(q,"opera software");var y=!/Chrome|CriOS|Skyfire/i.test(d)&&/Safari+\/[\.\d]+$/i.test(d)&&G;d=F&&(e(d,"IEMobile")||e(d,"WPDesktop"));var aa=y&&!("webkitRequestAnimationFrame"in
a),ba="screenX"in a,ca="outerWidth"in a,da="mozInnerScreenX"in a;A=A.msContentZoomFactor;var ea=!(!f.fireEvent||!f.attachEvent),Aa=u(a,"requestAnimationFrame"),fa=r&&!y&&!l.standalone,ha=n(a,"IntersectionObserver")&&!H;B=!!("srcdoc"in f.createElement("iframe"))&&e(B.href,"adform.com")&&!H;var O=r||M,p=w?a.top.omid3p:a.omid3p;if(!p)try{p=a.frames.omid_v1_present||a.top.frames.omid_v1_present}catch(b){}p=!!p;var ia=!p&&!O&&!d&&n(f,"hasFocus"),ja=!w&&11==W,z=a.wisp,ka=z&&z.sdk&&z.sdk.platform,la=y&&
!w,ma=a._adform&&a._adform.tagFrame,na=!!ma,oa=function(b){for(var c=k.length,g,m=0;m<c;m++)k[m]&&(g=b.mraid||g),b=b.parent;return g}(a),P=!!oa;l=l.sendBeacon&&!P;var pa=!(!a.XMLHttpRequest&&!l||!a.FormData)&&!a.XDomainRequest,Ba=function(){for(var b=a,c=t,g=k,m=1,E=g.length;m<E;m++)g[m]&&(b=c),c=c.parent;return b}(),Q=I&&t.getVPAIDAd&&t.getVPAIDAd(),qa=!(!Q||!Q.on),ra=!!a.chrome;f=""===f.referrer&&""===f.domain;C=a===C&&!!a.fence;var sa=!!n(a,"onpagehide");if("android"==ka||"ios"==ka)for(var ta in z)if(/^adObject.+/i.test(ta)){var ua=
z[ta].inscreen;var va=!!ua;break}return{result:[v,I,w,T,V,F,D,X,G,J,K,r,x,L,M,Y,N,H,Z,q,y,d,aa,ba,ca,da,A,ea,!1,fa,ha,B,O,p,ia,ja,va,la,na,P,l,pa,qa,ra,f,C,sa],exports:{nop:function(){},access:k,frame:v,accParent:I,accTop:w,isolate:T,hidden:U,hasHidden:V,isIE:F,ieVersion:W,addEvent:D,isMac:X,isApple:G,isIPad:J,isIPhone:K,isIOS:r,isIOSF:x,isGoogle:L,isAndroid:M,isTouch:Y,isChrome:N,chromeVersion:za,isFirefox:H,isOpera:Z,isOperaWebkit:q,isSafari:y,isIEMobile:d,isSafari5OrLess:aa,screenX:ba,outerWidth:ca,
mozInnerScreenX:da,msZF:A,ieDomEvents:ea,reqAni:Aa,isRad:!1,isIOSWebView:fa,intersectionAPI:ha,hasSrcDoc:B,isIOSOrAndroid:O,isOMID:p,hasFocus:ia,IEVisibility:ja,isWisp:va,wisp:ua,RAFVisibility:la,asyncFrame:ma,isAsyncFrame:na,mraid:oa,isMraid:P,hasBeacon:l,usePOST:pa,topAcc:Ba,VPAID:Q,isVPAID:qa,isChromium:ra,forceBackupEdge:f,isFencedFrame:C,usePageHide:sa}}}var wa={$hash:function(){if(!R){var h=ya(),u=h.result;h=h.exports;var n=[],e=0,a=u.length,f=0;for(a+=(6-a%6)%6;e<a;e++)f=f<<1|!!u[e],5==e%6&&
(n.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-".charAt(f)),f=0);for(e in h)wa[e]=h[e];R=n.join("")}return R}},R;try{if(!Function("return ("+xa+")(1)===1")())throw"Incorrect eval result";}catch(h){S.log("function_constructor",h)}return wa});
a(U,[c,i],function(g,h){function f(a){return k(a).random()}function k(a){var n={random:l,int32:function(){var e,m=[0,2567483615];if(624<=b)for(e=b=0;624>e;e++){var d=c[e]&2147483648|c[(e+1)%624]&2147483647;c[e]=c[(e+397)%624]^d>>>1^m[d&1]}d=c[b++];d^=d>>>11;d^=d<<7&2636928640;d^=d<<15&4022730752;return(d^d>>>18)>>>0}},c=[],b;a||(a=Math.round(1E5*((new Date).getTime()+Math.random())));c[0]=a>>>0;for(b=1;a=b-1,624>b;b++)a=c[a]^c[a]>>>30,c[b]=(1812433253*((a&4294901760)>>>16)<<16)+1812433253*
(a&65535)+b,c[b]>>>=0;return n}function l(){return Math.floor(this.int32()/65535)}h.random=g.deprecate(f,"Adform.random is deprecated. Use h/random instead.");return f});
a(R,[c,i],function(k,a){function m(e,c){var f=c?9==c.nodeType?c:c.document:n;0<=e.indexOf('"')&&k.log("xss_detected",e);f.write('<script type="text/javascript" src="'+e+'" attributionsrc>\x3c/script>')}function p(e){for(var c=a._prepareBannerDataCB,f={},d="ADFVideoCDN ADFDomainCDN ADFDomain VideoCDN ADFVideoCDNList ADFcmpgnID ADFmembID ADFtagID ADFafbanID ADFBanVer ADFBanVerBak ADFbanID ADFbanPlacID ADFUnloadID ADFClientSiteId ADFGeoData ADFDeviceType ADFGroupId ADFTemplateVersion ADFTemplateId ADF_ClickEvent".split(" "),
g=d.length-1;0<=g;g--)d[g]in h&&(f[d[g]]=h[d[g]]);var l=a.RMBData={clicktags:""};a._prepareBannerDataCB=function(){for(var b=d.length-1;0<=b;b--)d[b]in f&&(h[d[b]]=f[d[b]]);a.prepareBannerData(e);for(b in l)a.RMBData[b]="clicktags"!=b?l[b]:a.RMBData[b]+l[b];c&&c()};c||m(a.scriptBase+"bootstrap/Adform.BannerData.js?v="+a.cache)}var h=k.window,n=h.document;a.host&&(ADFDynamicDomain=a.host+"/banners/");a.shost&&(ADFTemplateDomain=a.shost+"/banners/");a.ENV={akamaiHost:("https:"==n.location.protocol?
"https://":"http://")+"s2.adform.net/Banners"};a.Log=a.Log||{sendMessage:k.log};a.loadResource=a.loadResource||m;a.prepareBannerData=a.prepareBannerData||p;return{loadResource:a.loadResource,prepareBannerData:a.prepareBannerData}});
a(T,function(){function f(a,c){this.delimiter=c||";";a=a||"";var b=a.split(";oobclicktrack=");b.shift();b.length&&(this.tracks=b);b=a.split("?");this._base=b.shift();this._parts=b.join("?").split(this.delimiter);this.append=[]}function g(a,c,b){var d=a.length;c+="=";var k=c.length;for(b||(c=c.toLowerCase());d--;){var h=a[d].slice(0,k);b||(h=h.toLowerCase());if(h===c)break}return d}var l=Object.prototype.hasOwnProperty,e=f.prototype;e.copy=function(){var a,c=new f;for(a in this)l.call(this,a)&&
(c[a]=this[a]&&this[a].slice?this[a].slice(0):this[a]);return c};e.get=function(a,c){var b=this._parts,d=g(b,a,c);if(~d)return b[d].slice(a.length+1)};e.set=function(a,c,b){var d=this._parts;b=g(d,a,b);0>b?d.push(a+"="+c):d[b]=d[b].slice(0,a.length+1)+c;return this};e.unset=function(a,c){var b=this._parts,d=g(b,a,c);~d&&b.splice(d,1);return this};e.toString=function(){return this._base+"?"+this._parts.join(this.delimiter)+this.append.join("")};return f});
a(V,[c,b,R],function(n,p,u){function v(c,a,e){var f="ADFP"+a.get("adfxid"),k="+"+f;c=c.replace("__ADFPAGEURL__",a.CREFURL);d.write('<div class="adServerCreativeContainer" id="'+f+'"><i id="'+k+'" style="display:none"></i></div><script src="'+c+'" data-ias-check-tag="true" data-ias-check-done="false" data-ias-container="'+f+'" data-ias-callback="'+e+'">\x3c/script>')}function w(c,a){if(b.replaceDocumentWrite&&d.writeln===d.write&&d.body)b[a]({block:!1});else{var e='<script type="text/adtag"><script>'+
a+"({block:false});</scr+ipt>\x3c/script>";q&&(e+='<script type="text/passback"><script>'+a+'({block:"P"});</scr+ipt>\x3c/script>');d.write(e);r(c);q||d.write("<script>"+a+'({block:"F"});\x3c/script>')}}var b=n.window,d=b.document,r=u.loadResource,q=p.isIE&&10>p.ieVersion,x=b.setTimeout,y=b.clearTimeout;return function(c,a){function e(g,z){y(A);g=!!g.block;b[h]=k;b.removeEventListener&&b.removeEventListener("pagehide",f,!0);g&&a.set("bsdata",a.BSDATA);var l=a.toString();if(z)(new b.Image).src=l;else if(B){var C=
"ADFP"+a.get("adfxid"),m=d.createElement("script");m.src=l;m.setAttribute("attributionsrc","");d.getElementById(C).appendChild(m)}else r(l)}function f(){b[h]({block:!0},!0)}function k(g){g&&g.block||n.log("dv_not_blocked",a.BN,1,"info")}var t=a.BSDATA,h="_adform_dv_"+ +new Date+"_"+(Math.random()+"").slice(2),B="ias"===t;b[h]=e;b.addEventListener&&b.addEventListener("pagehide",f,!0);var A=x(function(){b[h]({block:!1},!1)},5E3);switch(t){case "1":w(c,h);break;case "ias":v(c,a,h);break;default:e({block:!1})}}});
a(W,[c,b],function(m,f){function h(a,b){for(var c=[],d,g,e,k=0;k<a.length;k++)if(d=a[k])for(var l=0;l<b.length;l++)g=b[l],((e=d[g])||0==e)&&c.push(e);return c}return function(){if(!f.accTop)return"";if(f.isFencedFrame)return 0;var a=m.window.top,b=a.document,c=b.documentElement,d=b.body;b=h([a,c,d],["pageYOffset","scrollTop"])[0];var g=Math.max.apply(null,h([c,d],["scrollHeight","offsetHeight","clientHeight"]));a=h([a,c,d],["innerHeight","clientHeight"])[0];a=g==a&&0==b;if(!a&&f.isMraid)var e=
(f.mraid||{}).IS_GMA_SDK;return a||e?1:0}});
a(e,function(){function D(a,b){try{var c=a.frames}catch(e){}if(c){(b=b||[]).push(a);for(var d=0;c&&d<c.length;d++)D(a.frames[d],b)}return b}function E(a,b,c){b=void 0===b?1E4:b;c=void 0===c?!1:c;F();G();u||window.__tcfapi||m||window.__gpp?(c?k.push(a):l.push(a),x(),R(function(){var d=[v(l,a),v(k,a)],e=n("Adform",{}),f=e.gdpr,p=e.gdpr_consent,g=e.adform_consent,h=e.gpp;e=e.gpp_sid;if(-1<d[0])l.splice(d[0],1)[0]({gdpr:f,gdpr_consent:p,adform_consent:g,gpp:h,gpp_sid:e});if(-1<d[1])k.splice(d[1],1)[0]({gdpr:f,
gdpr_consent:p,adform_consent:g,gpp:h,gpp_sid:e})},b)):a(null,"CMP not found.")}function F(){var a=H("tcfapi"),b=a.isCrossDomain;u=a.frame;w=b;return{cmpFrame:u,isCrossDomainCmp:w}}function G(){var a=H("gpp"),b=a.isCrossDomain;m=a.frame;q=b;return{gppFrame:m,isCrossDomainGpp:q}}function H(a){if(!b&&(a=S("__"+a+"Locator"),a.frameRef))var b=a.frameRef,c=a.isCrossDomain;return{frame:b,isCrossDomain:c}}function x(){I("__tcfapi");I("__gpp")}function y(a,b){var c=a.api,d=a.frame,e=a.command,f=a.callback,
p=a.parameter,g="__gpp"===c;c+="Call";var h=window,L=g?J:K;h.removeEventListener?h.removeEventListener("message",L,!1):h.detachEvent&&h.detachEvent("onmessage",L);h=window;g=g?J:K;h.addEventListener?h.addEventListener("message",g,!1):h.attachEvent&&h.attachEvent("onmessage",g);g={};e=(g[c]={command:e,callId:z,parameter:p},g);A[z]="function"===typeof f?f:b;z++;d.postMessage(e,"*")}function J(a){if((a=a.data&&"string"===typeof a.data&&-1<a.data.indexOf("__gppReturn")?JSON.parse(a.data):a.data)&&a.__gppReturn&&
a.__gppReturn.callId&&(a=a.__gppReturn,A.hasOwnProperty(a.callId)))A[a.callId](a.returnValue)}function B(a,b){var c=a.api,d=a.frame,e=a.command,f=a.callback,p=a.parameter,g="__gpp"===c,h=g?q:w;(c=d&&!h?d[c]:window[c])&&(g?T({__api:c,command:e,callback:f,parameter:p,resultCallback:b}):U({__api:c,command:e,callback:f}))}function T(a){var b=a.__api,c=a.command,d=a.callback,e=a.parameter,f=a.resultCallback;r(function(){d?b(c,d):f(b(c,d,e))})}function U(a){var b=a.__api,c=a.command,d=a.callback;r(function(){b(c,
null,d)})}function I(a){var b="__gpp"===a,c=b?m:u;(b?q:w)&&c&&c.postMessage?y({api:a,frame:c,command:"addEventListener",callback:b?M:null}):B({api:a,frame:c,command:"addEventListener",callback:b?M:N})}function M(a){a&&("sectionChange"===a.eventName||a.pingData&&"loaded"===a.pingData.cmpStatus)&&(a=m,q&&a&&a.postMessage?y({api:"__gpp",frame:a,command:"getGPPData",callback:O}):B({api:"__gpp",frame:a,command:"getGPPData",callback:O}))}function K(a){var b=a.data;"string"===typeof b&&(b=r(function(){return window.JSON.parse(b)}));
b&&(b=(b.__tcfapiReturn||{}).returnValue);b&&null!=b.gdprApplies&&(a=b,N({gdprApplies:a.gdprApplies,tcString:a.tcString,purpose:a.purpose,vendor:a.vendor,restrictions:a.restrictions,eventStatus:a.eventStatus}))}function N(a){if((a=void 0===a?{}:a)&&"cmpuishown"!==a.eventStatus){var b=P(a.gdprApplies),c=n("Adform",{});c.gdpr=b;c.gdpr_consent=a.tcString;if(b=!(!a.purpose||!a.vendor)||0===b){var d=a;a=d.gdprApplies;var e=t(d,"purpose.consents.1",!1),f=t(d,"vendor.consents.50",!1);d=t(d,"restrictions.1.50",
1);a=0===P(a)?!0:e&&f&&0!==d;c.adform_consent=a}a=c.gdpr;e=c.gdpr_consent;f=c.adform_consent;d=c.gpp;c=c.gpp_sid;if(void 0!==f&&b)for(;k.length;)k.shift()({gdpr:a,gdpr_consent:e,adform_consent:f,gpp:d,gpp_sid:c});for(;l.length;)l.shift()({gdpr:a,gdpr_consent:e,adform_consent:f,gpp:d,gpp_sid:c})}}function O(a){if(a=void 0===a?{}:a){var b=q,c=m,d=n("Adform",{});a&&(d.gpp=a.gppString,d.gpp_sid=a.applicableSections&&a.applicableSections.join(","));if(a&&a.sectionList&&0<=v(a.sectionList,2))b&&c&&c.postMessage?
y({api:"__gpp",frame:c,command:"getSection",callback:Q,parameter:"tcfeuv2"}):B({api:"__gpp",frame:c,command:"getSection",parameter:"tcfeuv2"},Q);else{void 0===d.adform_consent&&(d.adform_consent=!0);a=d.gdpr;b=d.gdpr_consent;c=d.adform_consent;var e=d.gpp;for(d=d.gpp_sid;k.length;)k.shift()({gdpr:a,gdpr_consent:b,adform_consent:c,gpp:e,gpp_sid:d});for(;l.length;)l.shift()({gdpr:a,gdpr_consent:b,adform_consent:c,gpp:e,gpp_sid:d})}}}function Q(a){var b=n("Adform",{}),c=!!(a&&a.PurposeConsents&&a.VendorConsents);
if(c){var d=t(a,"PurposeConsents.1",!1),e=0<=v(a.VendorConsents,50)||!1;a=t(a,"PublisherRestrictions.1.50",1);b.adform_consent=d&&e&&0!==a}d=b.gdpr;e=b.gdpr_consent;a=b.adform_consent;var f=b.gpp;b=b.gpp_sid;if(void 0!==a&&c)for(;k.length;)k.shift()({gdpr:d,gdpr_consent:e,adform_consent:a,gpp:f,gpp_sid:b});for(;l.length;)l.shift()({gdpr:d,gdpr_consent:e,adform_consent:a,gpp:f,gpp_sid:b})}function P(a){if("1"==a)return 1;if("0"==a)return 0}function v(a,b){var c=a.length;if(a.indexOf)return a.indexOf(b);
for(;c--&&a[c]!==b;);return c}function t(a,b,c){b=b.split(".");for(var d=0;d<b.length;d++)if(a=a[b[d]],void 0===a){a=c;break}return a}var n=function(a,b){var c,d,e=D(window.top);for(c=e.length;c--;)try{if((d=e[c])&&(d=d[a])&&(d=d.shared))return d}catch(f){}return window[a].shared=b},r=function(a){try{return a()}catch(b){}},S=function(a){for(var b,c,d=window;d;){if(r(function(){return d.frames[a]})){b=d;break}if(d===V)break;d=d.parent}b&&(c=!r(function(){return!!b.document.getElementById}));return{frameRef:b,
isCrossDomain:c}},V=window.top,R=window.setTimeout,u,w,m,q,A={},z=1,l=[],k=[],C=window.Adform=window.Adform||{};C.getConsent=function(){x();var a=n("Adform",{});return{gdpr:a.gdpr,gdpr_consent:a.gdpr_consent,gpp:a.gpp,gpp_sid:a.gpp_sid}};C.waitForConsent=E;C.hasConsent=function(a){E(function(b){a(null===b?!0:b.adform_consent)},1E4,!0)};F();G();n("Adform",{});x();return window.Adform});
a(m,[c,i],function(S,J){function T(a,b,c){var d,f={autoPlay:1,loopVideo:1,soundOn:1,isStreaming:1};for(d in a){var g=a[d];"string"===typeof g?null!=b[d]&&(c[g]=f[g]?!!b[d]:b[d]):b[d]&&T(g,b[d],c)}}function U(){}function V(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function W(a,b){return(b=b||n)&&b.getElementById&&b.getElementById(a)}function E(a,b){var c=b?"string"==typeof a?W(a):a:n;return c?c.getElementsByTagName(b||a):[]}function F(a,b){return~(" "+a.className+
" ").indexOf(" "+b+" ")}function X(a,b){F(a,b)&&(a.className=(" "+a.className+" ").replace(" "+b+" "," ").slice(1,-1),X(a,b))}function ha(a,b){var c,d=a.ownerDocument.defaultView;d&&(d=d.getComputedStyle(a,null))&&(c=d.getPropertyValue(b.replace(ia,"-$1").toLowerCase()));return c||a.style[b]}function ja(a,b){var c,d=a.style,f=a.currentStyle&&a.currentStyle[b];if(!ka.test(f)&&la.test(f)){var g=d.left;if(c=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;d.left="fontSize"===
b?"1em":f||0;f=d.pixelLeft+"px";d.left=g;c&&(a.runtimeStyle.left=c)}return""===f?"auto":"curStyle"}function K(a){var b=a.offsetTop,c=a.offsetLeft,d,f=e.curCSS,g="static"!=f(a,"position");b||(b=(parseFloat(f(a,"marginTop"))||0)+(g?parseFloat(f(a,"top"))||0:0));c||(c=(parseFloat(f(a,"marginLeft"))||0)+(g?parseFloat(f(a,"left"))||0:0));g&&a.getBoundingClientRect&&(d=e.offset(a,!0));!b&&d&&(b=d.top);!c&&d&&(c=d.left);return{top:b,left:c}}function ma(a,b){var c=a&&a.ownerDocument;if(!c)return null;if(!b&&
a===c.body)return K(a);try{var d=a.getBoundingClientRect()}catch(g){}if(!d)return{top:0,left:0};var f=c.body;c=c.documentElement;return{top:d.top+(c.scrollTop||f.scrollTop)-(c.clientTop||f.clientTop||0),left:d.left+(c.scrollLeft||f.scrollLeft)-(c.clientLeft||f.clientLeft||0)}}function na(a){var b;var c=a&&a.ownerDocument;if(!c)return null;if(a===c.body)return K(a);var d=a.offsetParent;var f=c.documentElement;var g=c.body;var k=(c=c.defaultView)?c.getComputedStyle(a,null):a.currentStyle;var l=a.offsetTop;
var m=a.offsetLeft;for(b=Y();(a=a.parentNode)&&a!==g&&a!==f&&(!b.sfp||"fixed"!==k.position);)k=c?c.getComputedStyle(a,null):a.currentStyle,l-=a.scrollTop,m-=a.scrollLeft,a===d&&(l+=a.offsetTop,m+=a.offsetLeft,!b.dnab||b.dabftac&&oa.test(a.nodeName)||(l+=parseFloat(k.borderTopWidth)||0,m+=parseFloat(k.borderLeftWidth)||0),d=a.offsetParent),b.sbfonv&&"visible"!==k.overflow&&(l+=parseFloat(k.borderTopWidth)||0,m+=parseFloat(k.borderLeftWidth)||0);if("relative"===k.position||"static"===k.position)l+=
g.offsetTop,m+=g.offsetLeft;b.sfp&&"fixed"===k.position&&(l+=Math.max(f.scrollTop,g.scrollTop),m+=Math.max(f.scrollLeft,g.scrollLeft));return{top:l,left:m}}function pa(a){return"[object Array]"==Object.prototype.toString.call(a)}function Z(a){var b={relativeX:a[y[0]],relativeY:a[y[1]]};if(null==a.pageX&&null!=a.clientX){var c=n.documentElement;var d=n.body;b.pageX=a.clientX+(c&&c.scrollLeft||d.scrollLeft||0);b.pageY=a.clientY+(c&&c.scrollTop||d.scrollTop||0)}else b.pageX=a.pageX,b.pageY=a.pageY;return b}
function qa(a,b){var c,d=e.curCSS;a=a.parentNode;if(!a)return!1;if(p.$sf)return!0;var f=a.ownerDocument;var g=f.body;if(z&&(8>f.documentMode||"BackCompat"==f.compatMode))return!1;for(b&&(b+=1);a&&a!=g;){if("hidden"==d(a,"overflow"))return!1;if("fixed"==d(a,"position"))break;else if(b&&(c=parseInt(d(a,"z-index"),10))&&c<b)return!1;a=a.parentNode}return!0}function ra(){for(var a=0,b=[];a<v.length;a++)"complete"!=v[a].document.readyState&&b.push(v[a]);if(!(v=b).length||3E4<(new Date).getTime()-aa){A=
sa(A);for(a=0;a<G.length;a++)G[a]();G=[];v=[]}}function ba(a,b){var c=Math.max(a.x,b.x),d=Math.max(a.y,b.y),f=Math.min(a.x+a.width,b.x+b.width)-c,g=Math.min(a.y+a.height,b.y+b.height)-d;return 0<f&&0<g?{x:c,y:d,width:f,height:g}:{x:0,y:0,width:0,height:0}}function ca(a,b,c,d){var f=b.src||b.href;S.log("legacy_loadFile",f);var g=function(r){d&&d.apply(r,arguments)},k=E(c,"head");k=k&&k[0];if(!k)try{throw Error("Can't find head tag.");}catch(r){g(r)}var l=f.replace(/[^\da-z_-]/gi,"_"),m=c.adformId||
e.gid("doc_"),L=m+"|"+l,w=M[L];l=e.byTag(c,a);var t=0,N=l.length;c.adformId=c.adformId||m;if(w)w.loaded?g():w.callbacks.push(g);else{for(;t<N;++t)if(l[t].src==f||l[t].href==f){g();return}M[L]=w={doc:c,src:f,callbacks:[g]};var q=c.createElement(a);V(q,b);if(d){var O=function(r){q.onload=q.onreadystatechange=q.onerror=null;r?M[L]=null:w.loaded=1;var da=w.callbacks;t=0;for(N=da.length;t<N;++t)da[t](r)};q.onload=function(){O()};q.onreadystatechange=function(){"complete"==q.readyState&&O()};q.onerror=
function(){try{throw Error("Failed to load script: "+f);}catch(r){O(r)}}}P(function(){k.insertBefore(q,k.firstChild)},400)}}var A,aa,x,p=S.window,n=p.document,ta=p.setInterval,P=p.setTimeout,ua=p.clearTimeout,sa=p.clearInterval,H=p.navigator,va=Array.prototype.slice,v=[],G=[],M={},y=[["offsetX","offsetY"],["layerX","layerY"]],ia=/([A-Z])/g,ka=/^-?\d+(?:px)?$/i,la=/^-?\d/,oa=/^t(?:able|d|h)$/i,ea=n.defaultView,wa=n.createElement("div"),Y=function(){function a(){return a}var b=n.body,c=n.createElement("div");
var d=["position:absolute;top:0;left:0;margin:0;padding:0;border:0;width:1px;height:1px;"].pop();c.innerHTML='<div style="'+d+'visibility:hidden"><div style="'+d+'border:5px solid #000"><div style="margin:0"></div></div><div style="'+d+'"><div style="'+d+'position:fixed;top:20px;"></div></div><div style="'+d+'position:relative;border:5px solid #000;overflow:hidden"><div style="margin:0"></div></div><table style="'+d+'border:5px solid #000" cellpadding="0" cellspacing="0"><tr><td></td></tr></table></div>';
b.insertBefore(c=c.firstChild,b.firstChild);d=c.childNodes;a.dnab=5!==d[0].firstChild.offsetTop;a.sfp=20===d[1].firstChild.offsetTop;a.sbfonv=-5===d[2].firstChild.offsetTop;a.dabftac=5===E(c,"td").offsetTop;b.removeChild(c);b=c=d=null;return Y=a},B=H.vendor;var h=H.userAgent;var u=J.RMB,e=u.lib||(u.lib={}),C=/Apple Computer/i.test(B);u=/Google/i.test(B);var D=e.isIPad=/iPad/i.test(h),I=e.isIPhone=/iPhone/i.test(h);D=e.isIOS=D||I;var Q=e.isTouch="ontouchstart"in n.documentElement||"ontouchstart"in
p,xa=e.isOrientation="orientation"in p;I=e.isAndroid=!D&&/Android/i.test(h);var R=e.isMobile=/Mobile|Mobi|Tablet|Nokia/i.test(h)||Q,z=e.isIE=/msie|Trident/i.test(h);Q=e.isFF=/Firefox[\/.]+[^\s]/i.test(h);R=e.isWinPhone=z&&R&&/Phone/gi.test(h);var ya=e.isOpera=/Opera/i.test(h),za=e.isOperaMobile=/Opera\s(?!Mini)/i.test(h),Aa=e.isOperaMini=/Opera\sMini/i.test(h);B=e.isOperaWebKit=/OPR/i.test(h)&&/Opera Software/i.test(B);var fa=e.isChrome=/(Chrome|CriOS)+\/[\d\.]+\s/i.test(h)&&(D?C:u);C=e.isSafari=
!/Chrome|CriOS|Skyfire/i.test(h)&&/Safari+\/[\.\d]+$/i.test(h)&&C;u=e.isInternet=I&&!fa&&xa&&/Safari\/[\.\d]+$/i.test(h)&&u;var Ba=z?"msie":Q?"firefox":za?"operaMobile":Aa?"operaMini":ya?"opera":B?"operaWebKit":fa?"chrome":C?"safari":u?"internet":!1;e.isAndroidApp=I&&!/^(?:Opera|Mozilla)/i.test(h);e.isIOSF=D&&(x=/\sos\s(\d+)_\d+/i.exec(h))&&(x=4<x[1]>>0);e.isMACOS=/Mac OS X/i.test(h);R&&(x=/Windows Phone (OS )?(\d+[\.\d]*)/i.exec(h))&&x[2]&&(e.winPhoneVer=parseFloat(x[2]));e.isEdge=/Edge\/[\.\d]+$/i.test(h);
e.isAfmaSDK=/afma-sdk/i.test(h);e.browser=function(){return Ba};if(z&&("Microsoft Internet Explorer"==H.appName&&/MSIE (\d+[\.\d]*)/i.exec(h)||/rv:(\d+[\.\d]*)/i.exec(h)))var Ca=e.ieVersion=parseFloat(RegExp.$1);C&&(h=/Version.([\d.]+)/.exec(h),e.safariVersion=parseFloat(h&&h[1]));e.inherit=function(a,b){a.super_=b;U.prototype=b.prototype;a.prototype=new U;a.prototype.constructor=a};e.gid=function(a){var b=+new Date;return(a||"")+(b+b*~~(1E4*Math.random())).toString(36)};e.byId=W;e.byTag=E;e.bind=
function(a,b){return function(){return b.apply(a,arguments)}};e.extend=V;e.isMouseLeave=function(a,b){var c,d,f=b.length;if(a&&"mouseout"==a.type)for(c=a.relatedTarget||a.toElement;c;){for(d=0;d<f;d++)if(b[d]==c)return!1;c=c.parentNode}return!0};e.singleCall=function(a){function b(){g=!1;var k=d,l=c,m=f;c=d=f=null;k.apply(l,m)}var c,d,f,g;return function(k,l){c=k;d=l;f=va.call(arguments,2);l&&!g?g=P(b,a):!l&&g&&(ua(g),g=!1)}};e.onload=function(a,b){try{do{if(a.__adform_onload)break;a.__adform_onload=
!0;"complete"!=a.document.readyState&&(v.push(a),A||(aa=(new Date).getTime(),A=ta(ra,200)))}while(a!=a.parent&&(a=a.parent))}catch(c){}A?G.push(b):P(b,0)};e.overlap=ba;e.overlapElem=function(a,b){var c=e.offset(a),d=e.offset(b);return ba({x:c.left,y:c.top,width:a.offsetWidth,height:a.offsetHeight},{x:d.left,y:d.top,width:b.offsetWidth,height:b.offsetHeight})};e.hasClass=F;e.addClass=function(a,b){F(a,b)||(a.className+=" "+b)};e.removeClass=X;e.loadScript=function(a,b,c){ca("script",{src:b,type:"text/javascript"},
a,c)};e.loadCSS=function(a,b){ca("link",{href:b,type:"text/css",rel:"stylesheet"},a)};e.navigator=H;e.isTMX=function(a){var b,c,d=!1;try{d=(c=(b=a.document)&&b.body)&&F(c,"tmx")}catch(f){}return d};e.isolate=function(a,b){var c=a.__adform_isolate;if(!c){var d=a.document;c=E(d,"head")[0];d=d.createElement("script");d.type="text/javascript";d.text='function __adform_isolate(f){new Function("window","("+f+")(window)")(window)}';c.insertBefore(d,c.firstChild);c.removeChild(d);c=a.__adform_isolate}c?c(b):
(new Function("window","("+b+")(window)"))(a)};e.addEvent=function(a,b,c){return a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):!1};e.removeEvent=function(a,b,c){return a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent?a.detachEvent("on"+b,c):!1};e.curCSS=ea&&ea.getComputedStyle&&ha||n.documentElement.currentStyle&&ja;e.offsetFromWindow=function(a){var b=a&&a.ownerDocument;if(!b)return null;var c=b.documentElement;if("getBoundingClientRect"in c){try{var d=
a.getBoundingClientRect();var f=c.getBoundingClientRect()}catch(g){}if(!d)return{top:0,left:0};if(0<f.left||0<f.top)d.top-=f.top,d.left-=f.left;return{top:d.top,left:d.left}}d=b.defaultView||b.parentWindow;f=b.body;if(a===b.body)return K(a);a=e.offset(a);b=d&&d.pageYOffset||c.scrollTop||f.scrollTop;c=d&&d.pageXOffset||c.scrollLeft||f.scrollLeft;a.top-=b;a.left-=c;return a};e.offset="getBoundingClientRect"in n.documentElement?ma:na;e.client=function(a){a=a.ownerDocument||a;var b=a.defaultView||a.parentWindow;
var c=a.documentElement;var d=a.body;if(b.innerWidth){a=b.innerWidth;var f=b.innerHeight}else c?(a=c.clientWidth,f=c.clientHeight,a&&d.clientHeight==d.offsetHeight||(a=Math.min(a||123456789,d.clientWidth||123456789),f=Math.min(f||123456789,d.clientHeight||123456789))):(a=d.clientWidth,f=d.clientHeight);return{left:b&&b.pageXOffset||c&&c.scrollLeft||d&&d.scrollLeft||0,top:b&&b.pageYOffset||c&&c.scrollTop||d&&d.scrollTop||0,width:a,height:f}};e.isArray=Array.isArray||pa;e.getMousePos=function(a){for(var b;b=
y.shift();)if("undefined"!=typeof a[b[0]]){y=b;break}b||(y=["x","y"]);e.getMousePos=Z;return Z(a)};e.html=function(a,b){var c=!b&&wa||b.createElement("div");c.innerHTML=a;return c.firstChild&&c.removeChild(c.firstChild)};e.setMapValues=T;e.testPlace=z&&8>Ca?function(){return!1}:qa;e.indexOf=function(a,b){if(a.indexOf)return a.indexOf(b);var c;for(c=a.length;c--&&a[c]!==b;);return c};J.lib||(J.lib=e);return e});
a(Q,[c,m],function(t,u){function v(a){t.window.adfjsonbanners.push(a)}function n(a){var d,b,f,g=a.queue.length,c,h=a.queue,e=a.ready;for(d=0;d<g;d++){var k=h[d];for(b=0;b<e.length;b++)if((f=e[b])&&f.seqNo==k.seqNo){f.xId=k.xId;for(c=0;c<p.length;c++)delete f[p[c]];k.callback(f);h[d]=!1;e[b]=!1;break}}a.queue=q(h,Boolean);a.ready=q(e,Boolean);a.ready.length||(a.empty=!0)}function q(a,d,b){var f=0,g=a.length;b=b||null;if(a.filter)var c=a.filter(d,b);else for(c=[];f<g;f++)d.call(b,
a[f],f,a)&&c.push(a[f]);return c}var p=["csImpressionUrl","externalScripts","trackingPixelUrls"],w=u.indexOf;return{load:function(a,d,b,f){var g=a.sync[d],c=g&&g.loading;if(g){for(a=0;a<c.length;a++){var h=c[a];if(-1==w(h,b)){var e=!0;break}}e?e=!1:(e=!0,h=[],c.push(h))}else g=a.sync[d]=a.sync[1001]={queue:[],loading:[[]],ready:[]},e=!0,h=g.loading[0];g.queue.push({seqNo:b,xId:f,callback:v});if(g.ready.length)for(a=0;a<g.ready.length;a++)if(f=g.ready[a],f.seqNo==b){n(g);e=!1;break}else e=!0;else g.empty&&
(e=!0,g.empty=!1);(e||h.length)&&h.push(b);return e},run:function(a,d){var b=a.banner,f=b.innerBanners,g=f.length,c=d.loading;d.ready=d.ready||[];c.splice(0,1);c.length||d.loading.push([]);for(c=0;c<g;c++){var h=c+1;h={seqNo:h};for(var e in a)if(a.hasOwnProperty(e))if("banner"==e){var k=h.banner={};for(var l in b)"innerBanners"!=l&&(h.banner[l]=b[l]);var m=f[c];for(var r in m)k[r]=m[r];k.id=b.id;k.innerBannerId=m.id;k.asset&&(k.isRMB=!0)}else h[e]=a[e];d.empty=!1;d.ready.push(h)}n(d)}}});
a(O,[c,b,i,U,R,T,V,W,e,Q],function(t,u,m,B,f,H,U,V,I,W){function x(){if(y)return y;this.banners={};this.compoundBanners={};try{l.body||l.write('<html><body style="margin:0px;padding:0px;overflow:hidden;"></body></html>')}catch(c){}var a=r.browserLanguage||r.language||0;var b=this.getWin();this.settings=[v(r.systemLanguage||a),v(a),w?w.width+"X"+w.height:0,"",50*Math.round(b.w/
50),50*Math.round(b.h/50),w?w.colorDepth:0,8,3,7,this.hasIframeSanbox()].join("|")}function J(a,b,c){var d=(c=c||l).createElement("div");d.innerHTML='<iframe src="'+a+'" allowtransparency="true" webkitallowfullscreen mozallowfullscreen allowfullscreen marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no" width="1" height="1" style="'+b+'"></iframe>';c.body?c.body.appendChild(d.removeChild(d.firstChild)):c.documentElement&&(t.log("no_body",c.documentElement.innerHTML,
1),d.innerHTML="<body>"+d.innerHTML,c.documentElement.appendChild(d))}function X(a,b){var c=new H(a,"&"),d=c.get("gdpr"),e=c.get("gdpr_consent"),h=c.get("gpp");"0"==d||e||h?b(a):I.waitForConsent(function(g){if(g){if(g.gdpr||g.gdpr_consent)c.set("gdpr",g.gdpr),c.set("gdpr_consent",g.gdpr_consent||"");if(g.gpp||g.gpp_sid)c.set("gpp",g.gpp||""),c.set("gpp_sid",g.gpp_sid||"");b(c.toString())}else b(a)})}function Y(a){var b=u.asyncFrame;var c=a;if("undefined"!=typeof a.URL){try{var d=k.top.location.href.split("#")[0]}catch(e){d=
b||k,d=(b=(b=d.location.ancestorOrigins)&&b[b.length-1])||d.document.referrer}d=d?v(d):a.CREFURL;c=new H(a.URL);u.isFencedFrame||(c.append.push("&CREFURL="+d),c.CREFURL=d);c.BSURL=a.BSURL;c.BSDATA=a.BSDATA;c.BN=a.BN;c.READ_CONSENT=a.READ_CONSENT;c.ROTSEQ=a.ROTSEQ}return c}function K(a,b){var c=[[[a],0]];return function(d){var e,h;for(d&&(c=0);!e&&c;)if(h=c[0])if(d=h[0],h=h[1]++,h<d.length){try{var g=(e=d[h])&&e.frames||[];d[h]==b?e=0:e.Adform.ADFUtilInstance.getRotSeed.call}catch(z){e=0,g=g||[]}c.unshift([g,
0]);g=0}else c.shift();else c=0;return e&&e.Adform.ADFUtilInstance}}function L(a){return B(a+this.id)}function M(a){a=a.geoLocation||{};for(var b=[],c=0,d=["country","region","city"],e=d.length;c<e;c++){var h;(h=a[d[c]])&&"undefined"!==typeof h.id&&b.unshift(h.id)}return 3==b.length?b.join(";"):k.ADFGeoData}function N(a,b,c,d){"string"==typeof b&&(b=b.split(";"),3==b.length&&((new C).src=a+"/jsmetrics/?sid="+b[2]+"&rid="+b[1]+"&cid="+b[0]+c+(d?"&deviceType="+d:"")))}function D(){return(new Date).getTime()}
var y,q,A,E,k=t.window,Z=k.top,l=k.document,r=k.navigator,w=k.screen,C=k.Image,aa=Object.prototype.hasOwnProperty,ba=f.loadResource,v=k.encodeURIComponent,F=[];f=x.prototype;var O={webkitVisibilityState:"webkitvisibilitychange",mozVisibilityState:"mozvisibilitychange",msVisibilityState:"msvisibilitychange",visibilityState:"visibilitychange"};_adform=k._adform||[];if(m.ADFBannerUtils)return m.ADFBannerUtils;for(A in O)if(A in l){var P=A;var Q=O[A]}f.getCompoundBannerInfo=function(a){return this.compoundBanners["c"+
a]||null};f.createBanner=function(a){var b,c=this,d=c.getTagID(),e=c.addNewBanner(d,"undefined"==typeof m.ADFIframe?0:1);a=e.params=Y(a,c);var h=parseInt(a.get("compoundSeqNo"),10),g=a.BN,z=c.getCompoundBannerInfo(g),R=c.getPropByBn("smid",g),S=a.ROTSEQ,G=!0,T=a.BSURL,ca=a.READ_CONSENT;a.tracks&&(e.OOBClickTracks=a.tracks);a.get("singleTag")&&(e.singleTag=!0,h=h||1,a.set("compoundSeqNo",h));"prerender"==l[P]&&(a.set("hid",2),e.prerender=!0,l.addEventListener(Q,function(){"prerender"!=l[P]&&e.prerender&&
(l.removeEventListener(Q,arguments.callee,!1),c.registerImpression(e))},!1));if(h){e.compoundSeqNo=h;var p=c.getRotSeed();var n=p.gen(g);(G=W.load(p,g,h,d))||l.write('<div id="+ADFP'+d+'"></div>');p.compound[g]?b=p.compound[g]:S&&(p.compound[g]=S)}(p=a.get("compoundImpr"))?a.set("compoundImpr",1):0===p&&t.log("sync_copy",g,1);g=!0;for(p=0;p<a._parts.length;p++)"jsondebug=1"==a._parts[p]&&(g=!1);g&&a.set("json",1);a.set("js",1);a.set("adfxid",d);a.set(Math.floor(11E3*Math.random())+";set",c.settings+
"|"+V());n&&a.set("rotseed",n);b&&a.set("rotseq",v(b));z&&a.set("rotseqno",z.replace("r",""));R&&a.set("smid",R);m.CDNHost&&a.set("cdnhost",v(m.CDNHost));ca&&(n=I.getConsent(),a.set("cmpgdpr",void 0==n.gdpr?"":n.gdpr),a.set("cmpgdprconsent",void 0==n.gdpr_consent?"":n.gdpr_consent),a.set("cmpgpp",void 0==n.gpp?"":n.gpp),a.set("cmpgpp_sid",void 0==n.gpp_sid?"":n.gpp_sid));a.set("fd",u.accTop&&!u.isFencedFrame?""===Z.document.title?"2|2":"0|2":"0|0");a.get("studioid")&&(e.syncMembersCount=1,G=!0);n=
a.toString();T?U(T,a):G&&ba(n);return e};f.addNewBanner=function(a,b){return this.banners[a]={id:a,type:b,adfserveLoadTime:D()}};f.copyBanner=function(a,b){var c,d=this.banners[a];if(d=d&&d.params||null){d=d.copy();for(c in b)aa.call(b,c)&&d.set(c,b[c]);d=this.createBanner(d)}return d};f.wipeOutBanner=function(a){var b=this.banners[a];b&&(q&&(q.id=B(),q.compound&&delete q.compound[b.bn]),delete this.compoundBanners["c"+b.bn],delete this.banners[a])};f.addBannerAttribute=function(a,b,c){(a=this.banners[a])&&
(a[b]=c)};f.getTagID=function(){var a=this.getRotSeed();a.xId||(a.xId=0);return++a.xId+"x"};f.getRotSeed=function(){if(!q&&!E){E=!0;var a=K(k.top,k);var b=a();a(!0);b&&(q=b.getRotSeed());q?q.gen=L:q={sync:{},compound:{},id:B(),gen:L}}E=!1;return q};f.getFlashVersion=t.deprecate(function(){return null},"Utils_getFlash");f.getWin=function(){var a=l.documentElement,b=l.body;return{w:k.innerWidth||a&&a.clientWidth||b&&b.clientWidth,h:k.innerHeight||a&&a.clientHeight||b&&b.clientHeight}};f.getSettings=
function(){return this.settings};f.firePixel=function(a,b){var c="undefined"==typeof C?l.createElement("img"):new C;b&&"attributionSrc"in c&&(c.attributionSrc="");c.src=a};f.fireTargAdPixel=function(a){var b=this.TargAd||{};b[a]||((this.TargAd=b)[a]=!0,a=a.replace("{gmtr}",Math.floor(9999999999*Math.random())).replace("{gmttzd}",(new Date).getTimezoneOffset()),this.firePixel(a))};f.registerImpression=function(a){if(a&&a.prerender){var b=a.params.copy();b.set("hid",1);a.rotseqno&&b.set("rotseqno",
a.rotseqno);var c=l.createElement("script");c.src=b.toString();c.type="text/javascript";l.body.appendChild(c);delete a.prerender}};f.addCompoundBannerInfo=function(a,b){this.compoundBanners["c"+a]="r"+b};f.setBannerRegisteredStatus=function(a){var b,c=D(),d=c-a.adfserveLoadTime,e=parseInt(a.serverTime,10),h=m.ADFEventsInstance;a._host=m.host;a.adfserveLoadTime=d;e&&(e+=Math.round(.5*d),a.serverTime=e,a.timeDiff=e-c);a.registered=1;a.hash=this.getRotSeed().id;this.sendLoadMetrics(a);try{h&&h.register(a);
var g=0;for(b=F.length;g<b;g++)F[g].call(this)}catch(z){}};f.onBannerRegisteredStatus=t.deprecate(function(a){F.push(a)},"onreg_status",1);f.hasIframeSanbox=function(){var a=this._sandbox;if("number"!=typeof a){a=1;if(!u.isFencedFrame)try{k.top.document.getElementById,a=0}catch(b){}this._sandbox=a}return a};f.getPropByBn=function(a,b){var c,d=this.banners;for(c in d){var e=d[c];if(e.bn==b&&a in e)return e[a]}};f.now=D;f.getAdfscript=function(a){var b,c,d=/\/adfscript/,e=m.ADFIframe&&{src:k.location.href.replace(/cpjs=2/,
"cpjs=0")};if(!e){var h=l.getElementsByTagName("script");for(b=h.length;b--&&!e;)(c=h[b]).src&&c.src.match(d)&&-1<c.src.indexOf(a)&&(e=c)}return e||{}};f.getUnloadId=function(a){var b,c,d=K(k.top,k);for(b=y;b;){b=b.banners;for(c in b){var e=b[c];if(e.bn==a&&1==e.compoundSeqNo)return d(!0),e.interactionId}b=d()}};f.sendLoadMetrics=function(a){var b=(m.shost||"").split("/")[0]+"//"+"s2.adform.net/mink/636/s2.adform.net/load".replace("/load","")+"/bootstrap.js",c=k.performance;var d=(b=c&&c.getEntriesByName&&c.getEntriesByName(b))&&
b[0]&&b[0].duration;b=M(a);c=a.deviceType||k.ADFDeviceType;!a.metricsSent&&.1>Math.random()&&(d="&adfserve="+a.adfserveLoadTime+(d?"&asset="+parseInt(d,10):""),N(m.host,b,d,c));a.metricsSent=!0};f.sendVideoMetrics=function(a,b){var c=this.banners[a],d=M(c);c=c.deviceType||k.ADFDeviceType;.3>Math.random()&&N(m.host,d,"&video="+b,c)};f.loadFrame=J;f.loadTrackingIframes=function(a){var b=this.getRotSeed();if(a&&a.length&&!b.framesLoaded)for(b.framesLoaded=!0,b=a.length;b--;)X(a[b],function(c){J(c,"display:none")})};
f.ADFCreateObjectCallback=function(a,b){return function(){b.apply(a,arguments)}};f.eventRegister=function(){};f.getPosition=function(a){for(var b={x:0,y:0};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b};f.getScrollXY=function(){var a=l.body,b=l.documentElement,c={x:0,y:0};"number"==typeof k.pageYOffset?(c.y=k.pageYOffset,c.x=k.pageXOffset):a&&(a.scrollLeft||a.scrollTop)?(c.y=a.scrollTop,c.x=a.scrollLeft):b&&(b.scrollLeft||b.scrollTop)&&(c.y=b.scrollTop,c.x=b.scrollLeft);return c};
f.getBrowser=function(){try{var a=r.userAgent;return~r.appVersion.indexOf("MSIE")&&0>a.indexOf("Opera")?"MSIE":~a.indexOf("Safari")?"Safari":~a.indexOf("Opera")?"Opera":~a.indexOf("Netscape")?~r.product.indexOf("Gecko")&&(~r.vendor.indexOf("Firefox")||~a.indexOf("Firefox"))?"Firefox":"Netscape":void 0}catch(b){}};m.ADFUtilInstance=y=new x;return m.ADFBannerUtils=x.getInstance=x});
a(v,[c,b],function(c,d){return function(a,e){var b=c.window,f=b.navigator,g=b.Image;try{d.hasBeacon?f.sendBeacon(a,""):(new (e||b).Image).src=a}catch(h){(new g).src=a,c.log("beacon_failure",h+"_"+a,.1,"info")}}});
a(M,[c,i,O,v],function(d,f,k,v){var p=Object.prototype.hasOwnProperty,w=d.window.document;d={Initialized:!1,InitTime:(new Date).getTime(),Host:f.host||("https:"==w.location.protocol?"https://":"http://")+"track.adform.net",callbacks:[],sendEvent:function(b,a,g,q,r){var m=Math.round(((new Date).getTime()-this.InitTime)/1E3);var e=x.banners[b]||{};var c=e.banner||{};var n=e.publisher||{};var t=e.dsp||{},u=f.adRegister&&f.adRegister[b];try{this.notifyAboutEvent.apply(this,
arguments)}catch(y){}if(!c.tagId&&u)var h=u.sendEvent(a,g,q,r);else if(c&&c.isEventEnabled){h=c.tagId;e=["bn",h,"event",a,"time",(0>m?0:m)+"","baid",c.id,"innerbanner",c.innerBannerId,"asid",g,"name",q,"imprid",e.interactionId,"eData",e.eData,"adxvars",n.adxvars,"rtbdata",t.rtbdata,"rtbwp",t.rtbwp,"rnd",Math.floor(1E9*Math.random())];c=0;for(h=[];c<e.length;c+=2)(n=e[c+1])&&h.push(e[c]+"="+encodeURIComponent(n));h=(f.host||this.Host)+"/Serving/Event/?"+h.join("&")+(r||"");86400>m&&v(h)}return h},
Initialize:d.deprecate(function(){this.Initialized=!0},"initEvents",1),registerCallback:function(b,a){"function"==typeof b&&this.callbacks.push([b,a])},unregisterCallback:function(b){var a=this.callbacks,g=a.length;if("function"==typeof b)for(;g--;)a[g][0]==b&&a.splice(g,1)},notifyAboutEvent:function(){for(var b=this.callbacks.slice(),a=0,g=b.length;a<g;a++)b[a][0].apply(b[a][1]||this,arguments)}};var x=k();if(k=f.Events){for(var l in d)p.call(d,l)&&!p.call(k,l)&&(k[l]=d[l]);k.sendEvent=d.sendEvent}else k=
f.Events=d;f.ADFEvents2||(f.ADFEvents2=k);return d});
a(N,[c,i],function(e,a){function k(b){try{var d=b.URL,l=b.BN,m,f;b=/\/adfscript/;var g=a.ADFIframe&&{src:p.location.href.replace(/cpjs=2/,"cpjs=0")};if(!g){var c=h.getElementsByTagName("script");for(m=c.length;m--&&!g;)(f=c[m]).src&&f.src.match(b)&&-1<f.src.indexOf(l)&&(g=f)}var n=g||h.currentScript||{};var q=h.createElement("div");c=n;d=d.split(";");d[0]+=";srctype=6";for(d=d.join(";");c;){var r="BODY"==c.nodeName;var v="HEAD"==c.nodeName;c=!(r||v)&&c.parentNode}if(r){var t=n.parentNode;
var w=n}else t=h.body;q.innerHTML='<a href="'+a.host+"/C/?bn="+l+';C=0"><img src="'+d+'"></a>';t.insertBefore(q.firstChild,w||null);e.log("fallback",l)}catch(x){e.rethrow(x,"fallback_error")}}var u,p=e.window,h=p.document;e.require(["$ignore"],function(){var b=a.ADFBannerParams;u||(a.ADFUtilInstance||(a.ADFUtilInstance={}),a.ADFBanner||(a.ADFBanner=k),k(b&&b.length?b.shift():a.ADFBannerData))});return{cancel:function(){u=!0},write:k}});
a(x,[i],function(k){function f(){}function g(b){b?this._events&&this._events[b]&&delete this._events[b]:delete this._events;return this}function h(b){var a=this._events;a||(this._events=a={});return a[b]||(a[b]=[])}var l=Array.prototype.slice,e=f.prototype;k.RMB.EventEmitter=f;e.emit=function(b){var a,c,d=this._events;if(d&&(d=d[b])&&(c=d.length)){var m=l.call(arguments,1);d=d.slice();for(a=0;a<c;a++)d[a].apply(this,m)}return this};e.on=function(b,a){this.emit("newListener",b,a);h.call(this,
b).push(a);return this};e.once=function(b,a){var c=function(){return a.apply(this.off(b,c),arguments)};c._oncep=a;return this.on(b,c)};e.off=function(b,a){var c,d=(c=this._events)&&c[b];if(d){for(c=d.length;c--;)d[c]!=a&&d[c]._oncep!=a||d.splice(c,1);d.length||g.call(this,b);this.emit("removeListener",b,a)}return this};e.clear=g;e.list=h;return f});
a(y,[c],function(u){function n(g,h){for(var e in h)h.hasOwnProperty(e)&&("object"==typeof h[e]?("object"!=typeof g[e]&&(g[e]={}),n(g[e],h[e])):g[e]=h[e])}var r=u.window,x=r.parent,t={useClose:"expImage.useClose",overlay:"overlay",wallpaper:"options.wallpaper",x:"options.x",y:"options.y",hidden:"options.hidden",position:"options.position",adNotice:"options._adNotice",fixedBounding:"options.fixedBounding",resizeInFIF:"options.iabResize",panel:"panel",responsive:"options.responsive",testPlace:"options.testPlace"};
return function(g,h){var e,c,p,f,v;var a=g.options;var m=a.bn;try{var d=((a.iab?x:r)._adform||[]).slice(0)}catch(w){d=[]}var y=/(?:(\d+x|\d+#\d+|#[-_0-9a-z]+|\d+))?\.?(.*)/i,q={};a.iab&&d.push.apply(d,r._adform||[]);a.multiPanel&&("string"==typeof a.multiPanel&&(a.multiPanel=Function("return ("+a.multiPanel+")")()),d.push.apply(d,a.multiPanel));if(f=(a.userParams||{})._adform)try{if((f=Function("return ("+f+")")())&&"object"==typeof f)(d=d||[]).push([a.xId,f]);else throw Error("_adform from userParams should be an object");
}catch(w){u.rethrow(w,"user_params")}if("[object Array]"==Object.prototype.toString.call(d)&&d.length){f=h||["",m,"#"+a.seqNo,m+"#"+a.seqNo,a.xId];a=0;m=f.length;for(v=d.length;a<m;a++)q[f[a]]={};for(a=0;a<v;a++){var b=d[a][0].match(y);if(e=q[b[1]||""]){var k=d[a][1];if(b[2]){b=b[2].split(".");for(p=c={};1<b.length;)c=c[b.shift()]={};c[b[0]]=k;k=p}if(b=k.on)for(l in b){if("function"==typeof b[l])g.events.on(l,b[l])}else if(k.init)g.events.on("init",k.init);b={};for(c in k)t[c]&&(b[c]=k[c]);n(e,b)}}var l=
q[f[0]];for(a=1;a<m;a++)n(l,q[f[a]]);for(a in t)if(a in l){b=t[a].split(".");for(p=c={};1<b.length;)c=c[b.shift()]={};c[b[0]]=l[a];n(g,p)}}}});
a(S,[c,x,y,v],function(l,y,z,A){function B(a,b,d){a="<!DOCTYPE html><title>ad</title><body><script>inFIF=true;\x3c/script>"+a+"</body></html>";b=v('<iframe allowtransparency="true" webkitallowfullscreen mozallowfullscreen allowfullscreen marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no" width="1" height="1" style="width: '+(b.width+"px; height: "+b.height+'px;"></iframe>')).firstChild;b.src='javascript:document.write("'+
a.replace(/"/g,'\\"')+'");';h.getElementById(d).parentNode.appendChild(b)}function v(a){var b=h.createElement("div");b.innerHTML=a;return b}function C(a,b){var d=v(a),e=d.firstChild;e.innerHTML=b;return e.firstChild&&1==e.firstChild.nodeType?d.innerHTML:b}var q=l.window,h=q.document;return function(a){function b(f){w(["3rdparty/vendor/Adform"],function(r){r(a,f)})}var d=a.csImpressionUrl,e=q._adform=q._adform||[],g={options:a,events:new y};z(g,[a.banner.tagId]);try{g.events.emit("setup",g)}catch(f){l.rethrow(f,
"setup")}g=a.placeId="+ADFP"+a.xId;var c=a.banner.vendorName,m=a.banner.vendorCreativeId,k=["types/ThirdParty"],w=l.require,x=a.banner.dsa||{},t=a.params||{};h.getElementById(g)||h.write('<i id="'+g+'" style="display:none"></i>');x.dsaBuyerRenderRequired&&k.push("3rdparty/adNotice");c&&k.push("3rdparty/vendor/"+c);"Adform"==c&&m&&e.push([m+".on.setup",b]);w(k,function(f){f(a);for(var r=[].slice.call(arguments),n={},u,p=0;p<k.length;p++)u=k[p].split("/"),n[u[u.length-1]]=r[p];x.dsaBuyerRenderRequired&&
n.adNotice(a.banner);n.Adnami&&n.Adnami(a)});c=a.banner.script;e=a.banner.size;c=(m=a.wrapper)?C(m,c):c;t="ias"===t.BSDATA;try{t?B(c,e,g):h.write(c)}catch(f){l.rethrow(f,"thirdPartyWrite")}d&&A(d)}});
a(X,[c,b],function(l,m){function w(a){for(var g,e=0;e<a.length;e++)if("politeSrc"===a[e].name){g=a[e];break}return g}var q=l.window,h=q.document,x=q.setTimeout;m.$hash();return function(a){var g=new Date,e=m.isIE&&10>m.ieVersion,c=a.banner,n=c.assets||[],k=c.type,d=k.type,r=k.subType;k=a.xId;var f=(c.properties||{}).pushdown;c=c.size||{};var y={standard:1,expanding:1,singleExpanding:1}[d]&&![0,0,0,1,1][f];f=["AdConstructor","types/"+(4==f?"Slider":d.charAt(0).toUpperCase()+d.slice(1))];
if(n=w(n))d="polite",r=n.type;(d=({standard:{image:"contents/ImageTag",html:"contents/HTML"},floating:{image:"contents/ImageTag",html:"contents/HTML"},polite:{image:"contents/ImageTag"}}[d]||{})[r])&&f.push(d);y&&(a.placeId="+ADFP"+k,h.getElementById(a.placeId)||h.write('<div id="'+a.placeId+'"'+(a.singleTag?"":' style="width:'+c.width+"px;height:"+c.height+'px;"')+'></div><i style="display:none"></i>'));l.require(f,function t(p,u){var b=a.placeId;var v=p.cbuild,z="function"!==typeof u&&u;b?(b=h.getElementById(b)||
z)?(a.placement=b.nextSibling||b.previousSibling,b&&b.parentNode.removeChild(b),v(a)):1E4>new Date-g?x(function(){e&&a.iab?t(p,h.body.firstChild):t(p)},0):l.rethrow("Failed to find placement","noplacement"):v(a)})}});
a(P,[c,b,i,O,S,X,Q],function(r,E,u,F,G,l,H){function v(a){for(var b=0,e=a.length;b<e;b++)try{w(a[b])}catch(f){r.rethrow(f,"json_handle")}}function x(){I.apply(this,arguments);v(arguments)}function w(a){var b=a.xId,e=(a.visibility||{}).testMode,f=a.externalScripts||{},d=f.before,y=f.after,t=a.trackingPixelUrls,g=a.banner,h=g.type,q=h.type||h,z=g.size||{};h=(h=p.getElementById("+ADFP"+b))?h.parentNode:void 0;
var c=k.banners[b]||{},A=c.params&&"ias"===c.params.BSDATA;var m=g.type;var B=g.assets;m.subType?m=m.subType:B?(g.isRMB=!0,m=B[0].type):m=void 0;g.type={type:q,subType:m};d&&(C(d,h,A),a._beforeScript=!0,f.before=[]);k.loadTrackingIframes(a.trackingIframeUrls);J(c,a);c.bn=c.banner.tagId;c.adfxid=a.xId;c.type=q;c.width=z.width;c.height=z.height;k.setBannerRegisteredStatus(c);c.iab=!(!(n.inDapMgrIf||n.inDapIF||n.inFIF)||!E.accParent);if("synchronized"===q)if(d=k.getRotSeed().sync[c.banner.tagId],d._loaded&&
r.log("multiple_sync",c.banner.tagId,1),d._loaded=!0,g=g.innerBanners,c.syncMembersCount=f=g.length,H.run(a,d),c.singleTag&&1==c.compoundSeqNo)for(d=2;d<=f;d++)k.copyBanner(b,{compoundSeqNo:d,compoundImpr:0});else for(d=0;d<f;d++)a=d+1,g[d].floating&&c.compoundSeqNo!=a&&k.copyBanner(b,{compoundSeqNo:a,compoundImpr:0});else K[q](c);if(t)for(b=0,a=t.length;b<a;b++)k.fireTargAdPixel(t[b]);y&&C(y,h,A);e&&D(u.scriptBase+"unload/Adform.Inscreen.js?"+u.cache)}function C(a,b,e){e="loading"!=p.readyState||
e?D:L;for(var f=0;f<a.length;f++)e(a[f],b)}function D(a,b){b=b||p.body;var e=p.createElement("script");e.src=a;b.appendChild(e)}function L(a){p.write('<script src="'+a+'">\x3c/script>')}function M(a,b){for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e]);return a}var J=Object.assign||M,n=r.window,p=n.document,I=Array.prototype.push,k=F(),K={thirdparty:G,standard:l,expanding:l,tearback:l,floating:l,singleExpanding:l,interstitial:l};return function(){var a=n.adfjsonbanners;a?(a.push=x,v(a)):(a=[],a.push=
x,n.adfjsonbanners=a);return w}});
a(L,[c,i,M,N,O,P],function(f,a,g,e,h,k){function c(){var b=a.ADFBannerParams,d=b&&b.length?b.shift():a.ADFBannerData;if(d)try{h().createBanner(d)}catch(l){f.rethrow(l,"create_banner"),e.write(d)}b&&b.length&&c()}k();a.ADFBanner||(a.ADFBanner=c,a.ADFBanner());g.IE=9;e.cancel();return c});
a(f,function(){return"uEAv-wgQAAAAkAAA"});
})(_adfq.define,"Adform","$boot","$env","h/random","bootstrap/Global","bootstrap/URL","bootstrap/tagMeasurement","bootstrap/isAppView","consent-amd","common/lib","bootstrap/Compound","bootstrap/Utils","h/beacon","bootstrap/Events","bootstrap/Fallback","common/EventEmitter","api/ARMA","bootstrap/ThirdParty","bootstrap/typeLoader","bootstrap/responseHandler","bootstrap/Banner","$ignore");